from datetime import date, datetime
from decimal import Decimal
from typing import TYPE_CHECKING
from uuid import UUID, uuid4

from pydantic import Field

from bank_track.core.schemas.base import BaseDomainModel
from bank_track.core.schemas.types import CurrencyType

if TYPE_CHECKING:
    from bank_track.core.schemas.accounts import Account


class Balance(BaseDomainModel, use_enum_values=True):
    """The Balance model defining data provided by GoCardless API.

    The field `id` is generated by Pydantic using `uuid.uuid4` function.
    """

    id: UUID = Field(alias="balance_id", default_factory=uuid4)
    amount: Decimal = Field(decimal_places=2)
    currency: CurrencyType
    reference_date: date
    balance_type: str


class BalanceCreate(Balance):
    account_id: str
    user_id: str = Field(pattern=r"^user_[a-zA-Z0-9]{27}$")


class BalanceUpdate(Balance):
    account_id: str


class BalanceRead(Balance):
    account: "Account"
    created_at: datetime
