"""Adding user_id to all user-scoped models

Revision ID: 1ae59f5ce5a1
Revises: f067ce6c6b22
Create Date: 2025-04-07 18:51:09.032106

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1ae59f5ce5a1"
down_revision: Union[str, None] = "f067ce6c6b22"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("accounts", "provider_id", existing_type=sa.UUID(), nullable=False)
    op.alter_column("accounts", "name", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "accounts",
        "currency",
        existing_type=postgresql.ENUM(
            "EUR", "USD", "GBP", "UNKNOWN", "XXX", name="currencytype"
        ),
        nullable=False,
    )
    op.alter_column("accounts", "product", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "accounts",
        "account_type",
        existing_type=postgresql.ENUM(
            "CARD",
            "CURRENT",
            "CASH_PAYMENT",
            "CHARGES",
            "CASH_INCOME",
            "COMMISSION",
            "CLEARING_PARTICIPANT_SETTLEMENT_ACCOUNT",
            "LIMITED_LIQUIDITY_SAVINGS_ACCOUNT",
            "LOAN",
            "MARGINAL_LENDING",
            "MONEY_MARKET",
            "NON_RESIDENT_EXTERNAL",
            "OVERDRAFT",
            "OVER_NIGHT_DEPOSIT",
            "OTHER_ACCOUNT",
            "SETTLEMENT",
            "SALARY",
            "SAVINGS",
            "TAX",
            "TRANSACTING_ACCOUNT",
            name="cashaccounttype",
        ),
        nullable=False,
    )
    op.alter_column("accounts", "usage", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "accounts", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.alter_column(
        "accounts",
        "last_modified",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
    )
    op.alter_column("accounts", "access", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column("accounts", "user_id", existing_type=sa.TEXT(), nullable=False)
    op.add_column("balances", sa.Column("user_id", sa.Text(), nullable=False))
    op.alter_column(
        "balances",
        "amount",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        "balances",
        "currency",
        existing_type=postgresql.ENUM(
            "EUR", "USD", "GBP", "UNKNOWN", "XXX", name="currencytype"
        ),
        nullable=False,
    )
    op.alter_column(
        "balances", "reference_date", existing_type=sa.DATE(), nullable=False
    )
    op.alter_column(
        "balances", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.alter_column(
        "balances", "account_id", existing_type=sa.VARCHAR(), nullable=False
    )
    op.create_index(op.f("ix_balances_user_id"), "balances", ["user_id"], unique=False)
    op.create_foreign_key(None, "balances", "users", ["user_id"], ["user_id"])
    op.alter_column(
        "expense_categories",
        "category_name",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    op.alter_column(
        "expense_categories", "user_id", existing_type=sa.TEXT(), nullable=False
    )
    op.alter_column(
        "requisitions", "agreement_id", existing_type=sa.UUID(), nullable=False
    )
    op.alter_column(
        "requisitions", "accepted", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.alter_column(
        "requisitions", "institution_id", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "requisitions",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
    )
    op.alter_column(
        "requisitions",
        "last_modified",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
    )
    op.alter_column("requisitions", "user_id", existing_type=sa.TEXT(), nullable=False)
    op.add_column("transactions", sa.Column("user_id", sa.Text(), nullable=False))
    op.alter_column(
        "transactions",
        "amount",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        "transactions",
        "currency",
        existing_type=postgresql.ENUM(
            "EUR", "USD", "GBP", "UNKNOWN", "XXX", name="currencytype"
        ),
        nullable=False,
    )
    op.alter_column(
        "transactions", "booking_date", existing_type=sa.DATE(), nullable=False
    )
    op.alter_column(
        "transactions", "value_date", existing_type=sa.DATE(), nullable=False
    )
    op.alter_column(
        "transactions",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
    )
    op.alter_column(
        "transactions",
        "last_modified",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
    )
    op.create_index(
        op.f("ix_transactions_user_id"), "transactions", ["user_id"], unique=False
    )
    op.create_foreign_key(None, "transactions", "users", ["user_id"], ["user_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "transactions", type_="foreignkey")
    op.drop_index(op.f("ix_transactions_user_id"), table_name="transactions")
    op.alter_column(
        "transactions",
        "last_modified",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
    )
    op.alter_column(
        "transactions",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
    )
    op.alter_column(
        "transactions", "value_date", existing_type=sa.DATE(), nullable=True
    )
    op.alter_column(
        "transactions", "booking_date", existing_type=sa.DATE(), nullable=True
    )
    op.alter_column(
        "transactions",
        "currency",
        existing_type=postgresql.ENUM(
            "EUR", "USD", "GBP", "UNKNOWN", "XXX", name="currencytype"
        ),
        nullable=True,
    )
    op.alter_column(
        "transactions",
        "amount",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.drop_column("transactions", "user_id")
    op.alter_column("requisitions", "user_id", existing_type=sa.TEXT(), nullable=True)
    op.alter_column(
        "requisitions",
        "last_modified",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
    )
    op.alter_column(
        "requisitions",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
    )
    op.alter_column(
        "requisitions", "institution_id", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "requisitions", "accepted", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.alter_column(
        "requisitions", "agreement_id", existing_type=sa.UUID(), nullable=True
    )
    op.alter_column(
        "expense_categories", "user_id", existing_type=sa.TEXT(), nullable=True
    )
    op.alter_column(
        "expense_categories", "category_name", existing_type=sa.VARCHAR(), nullable=True
    )
    op.drop_constraint(None, "balances", type_="foreignkey")
    op.drop_index(op.f("ix_balances_user_id"), table_name="balances")
    op.alter_column("balances", "account_id", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "balances", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.alter_column(
        "balances", "reference_date", existing_type=sa.DATE(), nullable=True
    )
    op.alter_column(
        "balances",
        "currency",
        existing_type=postgresql.ENUM(
            "EUR", "USD", "GBP", "UNKNOWN", "XXX", name="currencytype"
        ),
        nullable=True,
    )
    op.alter_column(
        "balances",
        "amount",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.drop_column("balances", "user_id")
    op.alter_column("accounts", "user_id", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("accounts", "access", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column(
        "accounts", "last_modified", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.alter_column(
        "accounts", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.alter_column("accounts", "usage", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "accounts",
        "account_type",
        existing_type=postgresql.ENUM(
            "CARD",
            "CURRENT",
            "CASH_PAYMENT",
            "CHARGES",
            "CASH_INCOME",
            "COMMISSION",
            "CLEARING_PARTICIPANT_SETTLEMENT_ACCOUNT",
            "LIMITED_LIQUIDITY_SAVINGS_ACCOUNT",
            "LOAN",
            "MARGINAL_LENDING",
            "MONEY_MARKET",
            "NON_RESIDENT_EXTERNAL",
            "OVERDRAFT",
            "OVER_NIGHT_DEPOSIT",
            "OTHER_ACCOUNT",
            "SETTLEMENT",
            "SALARY",
            "SAVINGS",
            "TAX",
            "TRANSACTING_ACCOUNT",
            name="cashaccounttype",
        ),
        nullable=True,
    )
    op.alter_column("accounts", "product", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "accounts",
        "currency",
        existing_type=postgresql.ENUM(
            "EUR", "USD", "GBP", "UNKNOWN", "XXX", name="currencytype"
        ),
        nullable=True,
    )
    op.alter_column("accounts", "name", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("accounts", "provider_id", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###
